import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";

import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "داشبورد",
  description: "Generated by create next app",
};
const vazir = Vazirmatn({ subsets: ["arabic"], variable: "--font-vazir" });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`  ${vazir.variable}`}>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
        />
        <ToastContainer 
          position="top-center" 
          className={vazir.className} 
          rtl={true}
          toastClassName="!font-persian !text-right"
          bodyClassName="!font-persian !text-right"
          style={{ fontFamily: 'var(--font-hezare)' }}
        />

        {children}
      </body>
    </html>
  );
}
